### ISSUE TITLE
Module not found: Error: Can't resolve 'ws'

### ISSUE THREAD

**Issue by johncantrell97** [endel/tic-tac-toe#5]
Did the following:

git clone https://github.com/endel/tic-tac-toe
cd tic-tac-toe
cd frontend
npm install
npm start

I get this error:

ERROR in ./node_modules/@gamestdio/websocket/lib/index.js
Module not found: Error: Can't resolve 'ws' in '/Users/johncantrell97/Development/opensource/tic-tac-toe/frontend/node_modules/@gamestdio/websocket/lib'
 @ ./node_modules/@gamestdio/websocket/lib/index.js 1:837-850
 @ ./node_modules/colyseus.js/lib/Connection.js
 @ ./node_modules/colyseus.js/lib/Client.js
 @ ./node_modules/colyseus.js/lib/index.js
 @ ./src/Application.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.js
ℹ ｢wdm｣: Failed to compile.

Using node v11.10.0 (also tried with v8.11.4).
Using webpack 4.29.5

Any ideas? I feel like it has to be related to my node/webpack setup but I'm not sure what to try exactly.  I also tried downgrading webpack and webpack-cli to the min version specified in package.json without any luck (same error).

**Comment by endel** [comment]
Thanks a lot for reporting @johncantrell97, I've just fixed this on the latest version of `@gamestdio/websocket`. If you remove all `node_modules`, `package-lock.json` and install again, it should work fine!
